[workspace]

members = [
	"dmesg",
	"fdisk",
	"insmod",
	"login",
	"lsmod",
	"mkfs",
	"mount",
	"powerctl",
	"ps",
	"rmmod",
	"su",
	"umount",
	"usrgrp",
	"utils",
]

[profile.release]
lto = true
strip = true
