name: Check
on: push
jobs:
    Compilation:
        runs-on: [self-hosted, linux]
        steps:
            - uses: actions/checkout@v2
            - name: Debug
              run: cargo +nightly build
            - name: Release
              run: cargo +nightly build --release
    Test:
        runs-on: [self-hosted, linux]
        steps:
            - uses: actions/checkout@v2
            - name: Test
              run: cargo +nightly test
